In [1]:
import numpy as np

class Gaussian():
    def __init__(self,A):
        self.A = A
        self.m = len(A)
        self.n = len(A[0])
    
    def gaussian_LU_wo_pivot(self):
        k = 0
        for k in range(self.m):
            self.A[k+1:self.m+1, k] = self.A[k+1:self.m+1, k]/self.A[k][k]
            self.A[k+1:self.m+1, k+1:self.m+1] = self.A[k+1:self.m+1, k+1:self.m+1] - self.A[k+1:self.m+1, k].dot(self.A[k, k+1:self.m+1])

        L = np.eye(self.m) + np.tril(self.A, -1)
        U = np.triu(self.A)
        return L, U

    def gaussian_LU_w_pivot(self):
        k = 0
        p = np.eye(self.m, self.n)
        for k in range (self.m):
            r = max(enumerate(self.A.T[k][k:self.m]), key = lambda x: abs(x[1]))[0]
            q = r + k
            print(r, k, q)
            new_p, new_A = p[k], self.A[k]
            p[k], self.A[k] = p[q], self.A[q]
            p[q], self.A[q] = new_p, new_A
            if self.A[k][k] != 0:
                self.A[k+1:self.m+1, k] = self.A[k+1:self.m+1, k]/self.A[k][k]
                self.A[k+1:self.m+1, k+1:self.n+1] = self.A[k+1:self.m+1, k+1:self.n+1] - self.A[k+1:self.m+1, k] @ self.A[k, k+1:self.n+1]

        L = np.eye(self.m) + np.tril(self.A, -1)
        U = np.triu(self.A)
        return L, U
    def plsol(self):
        

In [2]:
a = np.array([[1,1,2],[4,-3,1],[-1,6,6]])
b = np.array([[1,3,2],[4,1,1],[0,0,1]])

In [3]:
G = Gaussian(a)
G.gaussian_LU_wo_pivot()

(array([[ 1.,  0.,  0.],
        [ 4.,  1.,  0.],
        [-1.,  0.,  1.]]),
 array([[ 1,  1,  2],
        [ 0, -5, -1],
        [ 0,  0,  4]]))

In [76]:
G.gaussian_LU_w_pivot()

1 0 1
1 1 2
0 2 2


(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 1.]]),
 array([[ 4, -5, -1],
        [ 0,  5,  9],
        [ 0,  0,  0]]))